---
name: generate-doc

on:
  workflow_dispatch: {}
  push:
    branches: [main]

jobs:
  check-generate-doc:
    uses: suzuki-shunsuke/yodoc-workflow/.github/workflows/create-pr.yaml@a4a52f7f0721f27de4fb1f1b69d0895de93463fa # v0.1.0
    permissions: {}
    with:
      base_branch: main
      author: 'suzuki-shunsuke-app[bot]'
      aqua_version: v2.44.0
    secrets:
      gh_app_id: ${{secrets.APP_ID}}
      gh_app_private_key: ${{secrets.APP_PRIVATE_KEY}}
