---
name: generate-doc

on:
  workflow_dispatch: {}
  push:
    branches: [main]

jobs:
  check-generate-doc:
    uses: suzuki-shunsuke/yodoc-workflow/.github/workflows/create-pr.yaml@first-pr
    with:
      base_branch: main
      author: 'suzuki-shunsuke-app[bot]'
      aqua_version: v2.29.0
    secrets:
      gh_app_id: ${{secrets.APP_ID}}
      gh_app_private_key: ${{secrets.APP_PRIVATE_KEY}}
